# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.2.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ".*svg"
      - id: mixed-line-ending
      - id: trailing-whitespace
      # - id: check-symlinks
      # - id: pretty-format-json
      # - id: sort-simple-yaml
  - repo: https://github.com/tcort/markdown-link-check
    rev: "v3.10.0"
    hooks:
      # https://github.com/tcort/markdown-link-check#config-file-format
      - id: markdown-link-check
        args: ["--config", ".markdown-link-check.json"]
  - repo: https://github.com/markdownlint/markdownlint
    rev: "v0.11.0"
    hooks:
      - id: markdownlint
        entry: mdl -r ~MD033,~MD013
        exclude: ^.github/
  - repo: local
    hooks:
      - id: check-github-workflows
        name: Validate GitHub Workflows
        description: 'Validate GitHub Workflows against the schema provided by SchemaStore'
        entry: check-jsonschema --builtin-schema vendor.github-workflows
        language: python
        files: ^\.github/workflows/
        types: [yaml]
      - id: black
        name: Black formatter
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: system
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
      - id: pycln
        name: Pyclean - Find redundant imports
        entry: pycln
        language: system
        pass_filenames: true
        types_or: [python, pyi]
      - id: mypy
        name: Mypy check
        entry: mypy
        language: system
        pass_filenames: true
        types_or: [python, pyi]
      - id: pyright
        name: Pyright check
        entry: pyright
        language: system
        pass_filenames: true
        types_or: [python, pyi]
      - id: pylint
        name: Pylint check
        entry: pylint
        language: system
        pass_filenames: true
        types: [python]
        exclude: ^tests/
      - id: ruff-format
        name: Ruff format check
        entry: ruff format --force-exclude --fix, --exit-non-zero-on-fix
        language: python
        types_or: [python, pyi]
      - id: ruff-lint
        name: Ruff lint check
        entry: ruff check --force-exclude --fix, --exit-non-zero-on-fix
        language: python
        types_or: [python, pyi]
      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
